name: Deploy Client

on:
  push:
    branches: [ "production" ]
    paths:
      - 'applications/client/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build client
        working_directory: application/client
        env:
          REACT_APP_URL: ${{ secrets.APP_URL }}
          REACT_APP_SERVER_URL: ${{ secrets.SERVER_URL }}
          REACT_APP_SOCKET_URL: ${{ secrets.SOCKET_URL }}
        run: npm run build

    deploy:
      runs-on: ubuntu-latest
      name: Deploy
      needs: build

      steps:
        - name: Deploy to Github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: applications/client/build
